[package]
name = "test-double-close"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["winerror"] }
windows = { version = "0.58.0", features = ["Win32_Foundation", "Win32_System_SystemServices", "Win32_Security", "Win32_Security_Cryptography"] }
